/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(align.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ae197aada4b71ba181571a8a8fe6f1fc) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/learning/align.h>
// pydoc.h is automatically generated in the build directory
#include <align_pydoc.h>

void bind_align(py::module &m) {

  using align = ::gr::learning::align;

  py::class_<align, gr::block, gr::basic_block, std::shared_ptr<align>>(
      m, "align", D(align))

      .def(py::init(&align::make), py::arg("tag_name"), py::arg("frame_size"),
           py::arg("label_frame_size"), py::arg("vec_len"),
           py::arg("user_symbols"), D(align, make))

      ;
}
